name: timemachine
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - jax=0.4.28
  - jaxlib=0.4.28=cpu*
  # Include numpy/scipy to reduce the size of the Docker container
  - numpy=2.2.2
  - scipy=1.15.1
