#!/usr/bin/env bash
set -e

MODULE=custom_ops

stubgen --output . --module "$MODULE"

# Workaround for
# > error: "ndarray" expects 2 type arguments, but 1 given
sed -i 's/numpy\.ndarray\[\([^]]*\)\]/numpy.typing.NDArray[\1]/g' "${MODULE}.pyi"
