# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parallel/service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parallel/service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16parallel/service.proto\"\x1c\n\nPickleData\x12\x0e\n\x06\x62inary\x18\x01 \x01(\x0c\"\x81\x01\n\x0fSimulateRequest\x12\x12\n\npotentials\x18\x01 \x01(\x0c\x12\x0c\n\x04lamb\x18\x02 \x01(\x01\x12\n\n\x02x0\x18\x03 \x01(\x0c\x12\n\n\x02v0\x18\x04 \x01(\x0c\x12\x0b\n\x03\x62ox\x18\x05 \x01(\x0c\x12\x13\n\x0b\x65quil_steps\x18\x06 \x01(\x05\x12\x12\n\nprod_steps\x18\x07 \x01(\x05\"\x1d\n\rSimulateReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32.\n\x06Worker\x12$\n\x06Submit\x12\x0b.PickleData\x1a\x0b.PickleData\"\x00\x62\x06proto3'
)




_PICKLEDATA = _descriptor.Descriptor(
  name='PickleData',
  full_name='PickleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='binary', full_name='PickleData.binary', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)


_SIMULATEREQUEST = _descriptor.Descriptor(
  name='SimulateRequest',
  full_name='SimulateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='potentials', full_name='SimulateRequest.potentials', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lamb', full_name='SimulateRequest.lamb', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x0', full_name='SimulateRequest.x0', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v0', full_name='SimulateRequest.v0', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box', full_name='SimulateRequest.box', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equil_steps', full_name='SimulateRequest.equil_steps', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prod_steps', full_name='SimulateRequest.prod_steps', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=186,
)


_SIMULATEREPLY = _descriptor.Descriptor(
  name='SimulateReply',
  full_name='SimulateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SimulateReply.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['PickleData'] = _PICKLEDATA
DESCRIPTOR.message_types_by_name['SimulateRequest'] = _SIMULATEREQUEST
DESCRIPTOR.message_types_by_name['SimulateReply'] = _SIMULATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PickleData = _reflection.GeneratedProtocolMessageType('PickleData', (_message.Message,), {
  'DESCRIPTOR' : _PICKLEDATA,
  '__module__' : 'parallel.service_pb2'
  # @@protoc_insertion_point(class_scope:PickleData)
  })
_sym_db.RegisterMessage(PickleData)

SimulateRequest = _reflection.GeneratedProtocolMessageType('SimulateRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATEREQUEST,
  '__module__' : 'parallel.service_pb2'
  # @@protoc_insertion_point(class_scope:SimulateRequest)
  })
_sym_db.RegisterMessage(SimulateRequest)

SimulateReply = _reflection.GeneratedProtocolMessageType('SimulateReply', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATEREPLY,
  '__module__' : 'parallel.service_pb2'
  # @@protoc_insertion_point(class_scope:SimulateReply)
  })
_sym_db.RegisterMessage(SimulateReply)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=219,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='Submit',
    full_name='Worker.Submit',
    index=0,
    containing_service=None,
    input_type=_PICKLEDATA,
    output_type=_PICKLEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
