---
map_generation:
  atom_mapping_strategy: geometry
  transformation_threshold: 3
  protein: datasets/fep-benchmark/hif2a/5tbm_prepared.pdb
  forcefield: ff/params/smirnoff_1_1_0_ccc.py
  ligands:
    - datasets/fep-benchmark/hif2a/ligands.sdf
  # Cores and hubs must be in the same order. 
  cores:
    - method: smarts
      smarts: "[*]~1~[*]~[*]~2~[*]~[*]~[*]~[*](~[#8]~[*]~3~[*]~[*]~[*]~[*]~[*]~3)~[*]~2~[*]~1"
    - method: smarts
      smarts: "[*]1~[*]~[*]~[*]~[*]~[*]1~[#8]~[*]2~[*]~[*]~[*]~[*]~[*]2"
  networks:
    - method: manual
      property: "ID"
      value: "165"
    - method: manual
      property: "ID"
      value: "41"
  output: relative_transformations.pkl
