name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'


jobs:

  test_no_gpu_nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax==0.4.38 jaxlib==0.4.38
        pip install -r requirements.txt
        CMAKE_ARGS=-DCUDA_ARCH=75 pip install -e .[dev,test,viz]

    - name: Run Nightly No GPU tests
      run: make nogpu_nightly_tests

  test_no_cuda_nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax==0.4.38 jaxlib==0.4.38
        pip install -r requirements.txt
        SKIP_CUSTOM_OPS=true pip install -e .[dev,test,viz]

    - name: Run Nightly No CUDA tests
      run: make nocuda_nightly_tests
