name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:

  test_no_gpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax==0.4.38 jaxlib==0.4.38
        pip install -r requirements.txt
        CMAKE_ARGS=-DCUDA_ARCH=75 pip install -e .[dev,test,viz]

    - name: Run No GPU Tests
      run: make nogpu_tests

  test_no_cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax==0.4.38 jaxlib==0.4.38
        pip install -r requirements.txt
        SKIP_CUSTOM_OPS=true pip install -e .[dev,test,viz]

    - name: Run No Cuda Tests
      run: make nocuda_tests
