name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CUDA_ARCH: all-major


jobs:

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Container
        run: docker build --build-arg $CUDA_ARCH -t timemachine_ci --target timemachine_ci .

  lint:
    runs-on: ubuntu-latest
    needs: build_docker
    container:
      image: timemachine_ci
      env:
        CUDA_ARCH: 75
    steps:
    - name: Run Lint
      run: make verify

  test_no_gpu:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: timemachine_ci
    steps:
    - name: Run No GPU Tests
      run: make nogpu_tests

  test_no_cuda:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: timemachine_ci
    steps:
    - name: Run No Cuda Tests
      run: |
        SKIP_CUSTOM_OPS=1 pip install .[test]
        make nocuda_tests
